# Generated by Django 4.1.1 on 2023-03-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена'),
        ),
    ]
